name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install -y meson valgrind
    - run: |
       meson _build
       cd _build
       ninja
       ninja test
       meson test --setup=valgrind
