name: C/C++ CI
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt install -y \
          meson \
          ninja-build \
          swig \
          python3-dev

    - name: Build
      run: |
        meson setup _build -Db_sanitize=address,undefined
        cd _build
        meson compile -v

    - name: Test
      run:  |
        cd _build
        meson test -v

    - name: Test swig
      run:  |
        cd _build
        meson configure -Dswig_lang=python
        ninja clean
        ninja -v
