name: Linux
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
    paths:
    - '**'
    - '!**.yml'
    - '!**.md'
    - '**/linux.yml'

  pull_request:
    branches: [ master ]
    paths:
    - '**'
    - '!**.yml'
    - '!**.md'
    - '**/linux.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt install -y \
          meson \
          ninja-build \
          swig \
          python3-dev

    - name: Meson setup
      run: CFLAGS="-Werror" meson setup _build -Db_sanitize=address,undefined

    - name: Build
      run: meson compile -C _build

    - name: Test
      run:  |
        cd _build
        meson test -v

    - name: Test swig
      run:  |
        meson setup _build --reconfigure -Dswig_lang=python
        meson compile -C _build
