name: Windows
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
    paths:
    - '**'
    - '!**.yml'
    - '!**.md'
    - '**/windows.yml'

  pull_request:
    branches: [ master ]
    paths:
    - '**'
    - '!**.yml'
    - '!**.md'
    - '**/windows.yml'

jobs:
  MSYS2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        pacboy: >-
          gcc:p
          ninja:p
          meson:p
        update: true

    - name: Meson setup
      shell: msys2 {0}
      run: |
        CFLAGS="-Werror" meson setup _build

    - name: Build
      shell: msys2 {0}
      run: |
        meson compile -C _build

    - name: Test
      shell: msys2 {0}
      run: |
        meson test -v -C _build
